// react-app/src/components/agegate.component.js
import React, { useState } from "react";
import ReactDOM from "react-dom";

export default function Agegate(props) {
    const [adult,setAdult] = useState(null);

    function checkAge() {
        let day = parseFloat(document.getElementById('day').value);
        let month = parseFloat(document.getElementById('month').value);
        let year = parseFloat(document.getElementById('year').value);
        let currentYear = new Date();
        let born = new Date(year, month-1, day);
        let age = get_age(born,currentYear);
        let dateToLocal = born.getTime();
        if(isValidDate(year, month-1, day)) {
            if (age < 18) {
                setAdult(false);
            } else if(age > 120){
                setAdult('invalid');
            } else {
                setAdult(true);
                setCookie("anonymousUserBirthDate", dateToLocal, 30);
                //window.localStorage.setItem('anonymousUserBirthDate',dateToLocal);
                props.saveBirthDate(dateToLocal);
            }
        } else {
            setAdult('invalid');
        }
        
    }
    function get_age(born, now) {
        var birthday = new Date(now.getFullYear(), born.getMonth(), born.getDate());
        if (now >= birthday) {
            return now.getFullYear() - born.getFullYear();
        } else {
            return now.getFullYear() - born.getFullYear() - 1;
        }
    }
    function isValidDate(year, month, day) {
        var d = new Date(year, month, day);
        if (d.getFullYear() == year && d.getMonth() == month && d.getDate() == day) {
            return true;
        }
        return false;
    }

    function setCookie(accept,cvalue,exdays) {
        let d = new Date();
        d.setTime(d.getTime() + (exdays*24*60*60*1000));
        let expires = "expires=" + d.toGMTString();
        document.cookie = accept + "=" + cvalue + ";" + expires + ";path=/";
    }

    return (
        <div id='agegate' className='agegate row center-sm middle-sm'>
            <div className='container center-xs row'>
                <div className='agegate__content col-xs-12 col-lg-7 center-xs middle-sm top-xs row'>
                    <div>
                        <p className="section__text">¡Hola!</p>
                        <p className="section__text">Por favor ingresa tu fecha de nacimiento</p>
                        <p className="section__text cookies-policies">Debes ser mayor de 18 años para acceder. Al ingresar, aceptas que utilizamos cookies para personalizar contenido y anuncios, proporcionar funciones de redes sociales y analizar nuestro tráfico. También compartimos información sobre cómo usted utiliza nuestro sitio con nuestros socios de redes sociales, de publicidad y de analítica.</p>
                        <form className='agegate__form row center-xs middle-xs'>
                            <input type="text" maxLength="2" placeholder="DD" id="day" />
                            <input type="text" maxLength="2" placeholder="MM" id="month" />
                            <input type="text" maxLength="4" placeholder="AAAA" id="year" />
                            {
                                adult == false?
                                    <p className="section__text col-xs-12">Debes ser mayor de 18 años para acceder</p>
                                :
                                adult == 'invalid'?
                                    <p className="section__text col-xs-12">Por favor ingresa una fecha válida</p>
                                :
                                null
                            }
                            <div className="col-xs-12 center-xs">
                                <input className="section__button" type="button" onClick={()=>checkAge()} value="Enviar" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    )
    

}

// home/src/app/age-gate/age-gate.component.ts
import { Component, TemplateRef, ViewChild } from '@angular/core';
import { NgbModal, ModalDismissReasons } from '@ng-bootstrap/ng-bootstrap';
import { BirthDate } from './BirthDate';
import { CookieService } from "ngx-cookie-universal";

@Component({
  selector: 'app-age-gate',
  templateUrl: './age-gate.component.html',
  styleUrls: ['./age-gate.component.scss']
})
export class AgeGateComponent {
  closeResult: string;
  @ViewChild('ageGate', { read: TemplateRef }) private ageGate:TemplateRef<any>;
  birthdate: BirthDate = {};
  isAdult: any = null;

  constructor(
    private modalService: NgbModal,
    private cookies: CookieService
  ) { }

  public openAgeGate() {
    this.openModal(this.ageGate);
  }

  private openModal(content: any) {
    const modalConfig = {
      ariaLabelledBy: 'modal-basic-title',
      ignoreBackdropClick: true,
      keyboard: false
    }
    this.modalService.open(content, modalConfig).result.then((result) => {
      this.closeResult = `Closed with: ${result}`;
    }, (reason) => {
      this.closeResult = `Dismissed ${this.getDismissReason(reason)}`;
    });
  }

  private getDismissReason(reason: any): string {
    if (reason === ModalDismissReasons.ESC) {
      return 'by pressing ESC';
    } else if (reason === ModalDismissReasons.BACKDROP_CLICK) {
      return 'by clicking on a backdrop';
    } else {
      return  `with: ${reason}`;
    }
  }

  checkAge():void {
    let day = this.birthdate.day;
    let month = this.birthdate.month;
    let year = this.birthdate.year;
    let currentYear = new Date();
    let born = new Date(year, month - 1, day);
    let age = this.get_age(born, currentYear);
    let dateToLocal = born.getTime();
    if (this.isValidDate(year, month - 1, day)) {
      if (age < 18) {
        this.isAdult = false;
      } else if (age > 120) {
        this.isAdult = 'invalid';
      } else {
        this.isAdult = true;
        this.cookies.put('anonymousUserBirthDate', dateToLocal.toString());
        this.modalService.dismissAll();
      }
    } else {
      this.isAdult = 'invalid';
    }
  }

  private get_age(born: any, now: any) {
    var birthday = new Date(now.getFullYear(), born.getMonth(), born.getDate());
    if (now >= birthday) {
      return now.getFullYear() - born.getFullYear();
    } else {
      return now.getFullYear() - born.getFullYear() - 1;
    }
  }

  private isValidDate(year: any, month: any, day: any) {
    var d = new Date(year, month, day);
    if (d.getFullYear() == year && d.getMonth() == month && d.getDate() == day) {
      return true;
    }
    return false;
  }

}

<ng-template #ageGate let-modal>
  <div id='agegate-modal' class='agegate row center-sm middle-sm bg-black bg-opacity-60 h-full left-2 fixed top-0 w-full z-10'>
    <div class='container center-xs row'>
      <div class='agegate__content col-xs-12 col-lg-7 center-xs middle-sm top-xs row bg-white'>
        <div>
          <p class="section__text">¡Hola!</p>
          <p class="section__text">Por favor ingresa tu fecha de nacimiento</p>
          <p class="section__text text-sm cookies-policies">Debes ser mayor de 18 años para acceder. Al ingresar, aceptas
            que utilizamos cookies para personalizar contenido y anuncios, proporcionar funciones de redes sociales y
            analizar nuestro tráfico. También compartimos información sobre cómo usted utiliza nuestro sitio con
            nuestros socios de redes sociales, de publicidad y de analítica.</p>
          <form class='agegate__form row center-xs middle-xs' #ageGateForm="ngForm" (ngSubmit)="checkAge()">
            <input type="text" maxLength="2" placeholder="DD" label-for="day" id="day" name="day" [(ngModel)]="birthdate.day"/>
            <input type="text" maxLength="2" placeholder="MM" label-for="month" id="month" name="month" [(ngModel)]="birthdate.month"/>
            <input type="text" maxLength="4" placeholder="AAAA" label-for="year" id="year" name="year" [(ngModel)]="birthdate.year"/>
            
            <p *ngIf="isAdult == false" class="section__text col-xs-12">Debes ser mayor de 18 años para acceder</p>
            <p *ngIf="isAdult == 'invalid'" class="section__text col-xs-12">Por favor ingresa una fecha válida</p>
            <div class="col-xs-12 center-xs">
              <button class="section__button bg-primary-500 text-white leading-4" type="submit" [disabled]="!ageGateForm.valid">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</ng-template>
