// home/src/app/footer/footer.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {
  isAndroid= false;
  isIOs = false;
  isOnWebView: boolean = false;

  constructor() {
  }

  detectMobileDevice(){
    if(navigator.userAgent.match(/Android/i)){
      this.isAndroid = true;
    } else if(navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i)) {
      this.isIOs = true;
    }
  }
  

  ngOnInit() {
    this.detectMobileDevice();
  }

}

<footer
  class="bg-neutral-100 w-full sm:mt-10 bg-right-bottom sm:bg-right bg-no-repeat bg-contain sm:bg-auto bg-footer border-t-2 border-primary-500">
  <div class="container pt-8 px-4 md:px-0 mx-auto">
    <div class="w-full sm:w-9/12 xl:w-9/12 px-2 inline-block">
      <div class="inline-block align-top"><p class="text-primary-500 uppercase mb-6 font-bold text-xs tracking-widest">
        Acerca de Tapit</p>
        <div class="w-1/2 inline-block align-top">
          <ul class="text-secondary-500">
            <li class="w-full inline-block align-top sm:pb-0 pb-3 mb-5"><a href="/terms.html" target="_blank">Términos y
              Condiciones</a></li>
            <li class="w-full inline-block align-top sm:pb-0 pb-3 mb-5"><a href="/cookies.html" target="_blank">Política
              de Cookies</a></li>
          </ul>
        </div>
        <div class="w-1/2 inline-block align-top">
          <ul class="text-secondary-500">
            <li class="w-full inline-block align-top sm:pb-0 pb-3 mb-5"><a href="/privacy.html" target="_blank">Aviso de
              privacidad</a></li>
            <li class="w-full inline-block align-top sm:pb-0 pb-3 mb-5"><a href="/data-proteccion.html" target="_blank">Políticas
              de protección de datos personales</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="w-full sm:w-9/12 xl:w-9/12 px-2 inline-block pt-4">
      <div class="inline-block align-top w-full"><p
        class="text-primary-500 uppercase mb-6 font-bold text-xs tracking-widest">Soporte</p>
        <div class="w-1/2 inline-block align-top">
          <ul class="text-secondary-500">
            <li class="w-full inline-block align-top sm:pb-0 pb-3 mb-5"><a href="https://tapit.zendesk.com/hc/es-419" target="_blank">Preguntas Frecuentes</a>
            </li>
            <li class="w-full inline-block align-top sm:pb-0 pb-3 mb-5"><a href="https://tapit.zendesk.com/hc/es-419/requests/new" target="_blank">Contáctanos aqui</a>
            </li>
          </ul>
        </div>
        <div class="w-1/2 inline-block align-top md:-ml-24">
          <ul class="text-secondary-500">
            <li class="w-full inline-block align-top sm:pb-0 pb-3 mb-5"><a href="/cancellation-policies.html" target="_blank">Políticas de cancelación</a></li>
            <li class="w-full inline-block align-top sm:pb-0 pb-3 mb-5"><a href="/help.html" target="_blank">Recomendaciones
              Covid-19</a></li>
          </ul>
        </div>
        <div class="w-1/2 inline-block align-top">
          <ul class="text-secondary-500">
            <li class="mb-5 md:w-1/2 w-full inline-block"><a href="https://www.sic.gov.co/por-un-clic-confiable" target="_blank">
              <img
                class="inline-block align-middle logo-sic" src="../assets/images/logo-sic-footer.png"></a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="w-full sm:w-3/12 xl:w-3/12 inline-block align-top px-2"><p
      class="text-primary-500 uppercase mb-6 font-bold text-xs tracking-widest">Siguenos en</p>
      <ul class="text-secondary-500">
        <li class="mb-5 w-1/2 sm:w-full inline-block"><a href="https://www.facebook.com/gettap.it/" target="_blank">
          <img
            class="inline-block align-middle" src="../assets/images/footer/facebook-logo.svg"><span
          class="align-middle ml-3">Facebook</span></a></li>
        <li class="mb-5 w-1/2 sm:w-full inline-block"><a href="https://www.instagram.com/tapit_beer/"
                                                         target="_blank">
          <img class="inline-block align-middle"
               src="../assets/images/footer/instagram-logo.svg"><span
          class="align-middle ml-3">Instagram</span></a></li>
      </ul>
    </div>

    <section class="container px-2 transform mx-auto mt-2">
      <div class="bg-neutral-100 w-full md:w-11/12 lg:w-8/12 xl:w-6/12 py-8 border-4 border-white shadow-sm">
        <div class="w-11/12 mx-auto">
          <div class="w-full sm:w-7/12 inline-block align-top"><p class="text-primary-500 font-bold ">Descarga la
            app</p>
            <p class="mb-3 text-sm">Para verdaderos amantes de la cerveza</p>
            <div class="hidden sm:block">
              <div class="">
                <div class="inline-block"><a href="https://apps.apple.com/us/app/tapit/id1481852424?ls=1"
                                             target="_blank">
                  <img src="../assets/images/download/appStore.svg"></a>
                </div>
                <div class="inline-block ml-3"><a href="https://play.google.com/store/apps/details?id=com.abinbev.tapit"
                                                  target="_blank">
                  <img
                    src="../assets/images/download/googlePlay.svg"></a></div>
              </div>
              <p class="inline-block text-neutral-700 align-middle text-xs">* Disponible únicamente para dispositivos
                móviles</p></div>
            <div *ngIf="isIOs" class="mt-4 block">
              <div class="inline-block"><a href="https://apps.apple.com/us/app/tapit/id1481852424?ls=1"
                target="_blank"><img src="../assets/images/download/appStore.svg"></a></div>
            </div>
            <div *ngIf="isAndroid" class="mt-4 block">
              <div class="inline-block"><a href="https://play.google.com/store/apps/details?id=com.abinbev.tapit"
                target="_blank"><img src="../assets/images/download/googlePlay.svg"></a></div>
            </div>
          </div>
          <div class="w-full sm:w-5/12 sm:inline-block align-top hidden">
            <div class="w-1/2 inline-block align-top text-xs text-neutral-700"><p>O escanea este código QR con tu
              teléfono móvil para descargar la app.</p></div>
            <div class="w-1/2 inline-block align-top pl-4">
              <img class="max-w-none"
                   src="../assets/images/download/onlink_to_9mttry.svg"
                   width="120"></div>
          </div>
          <div class="clear-both"></div>
        </div>
      </div>
    </section>
    <div class="block md:hidden visible px-5 mt-6"><p class="text-neutral-black text-xs">Company info: <br/> ZX VENTURES COLOMBIA S.A.S.NIT: 830.094.751-7  <br/>   Dirección: Cra 53ª No. 127 – 35, Bogotá.  <br/>   Correo electrónico para notificaciones: impuestos@bogotabeercompany.com </p></div>
    <div class="hidden sm:block mt-6 w-11/12"><p class="flex justify-between text-neutral-black text-xs"><span class="text-secondary-500">Company info: ZX VENTURES COLOMBIA S.A.S.NIT: 830.094.751-7</span>    <span class="text-secondary-500">Dirección: Cra 53ª No. 127 – 35, Bogotá.</span>  <span class="text-secondary-500">Correo electrónico para notificaciones: impuestos@bogotabeercompany.com</span> </p></div>
    <div class="border-t-2 border-neutral-500 py-5 px-5 md:px-0 mt-8 md:mt-12 flex flex-wrap">
      <div class="w-full mt-4 sm:mt-1 order-1 md:w-1/3 sm:w-3/5">
        <img class="inline-block align-middle"
             src="https://market.tapit.com.co/arquivos/tap-it_black-orange.png"/>
        <p class="inline-block text-neutral-700 ml-1 pl-2 border-l border-neutral-600 align-middle text-xs"><span class="text-neutral-700">Todos los derechos reservados © 2021</span>
        </p></div>
        <div
        class="w-full mt-4 sm:mt-1 order-1 sm:order-5 sm:w-3/5 md:order-2 md:w-1/3 md:pl-12 text-xs text-neutral-700">
        El exceso de alcohol es perjudicial para la salud.
      </div>
      <div class="w-full mt-4 sm:mt-1 order-2 sm:order-3 sm:w-3/5 md:order-4 md:w-1/3 text-xs text-neutral-700">
        Prohíbase el expendio de bebidas embriagantes a menores de edad.
      </div>
      <div
        class="w-full mt-4 sm:mt-1 order-4 sm:order-2 sm:w-2/5 sm:pl-4 md:order-5 md:w-1/3 md:pl-12 text-xs text-neutral-700">
        No comparta este contenido con menores de edad.
      </div>
      <div
        class="w-full mt-4 sm:mt-1 order-5 sm:order-4 sm:w-2/5 sm:pl-4 md:order-3 md:w-1/3 md:pl-2 text-xs text-black font-bold">
        <span class="inline-block align-middle">www.hablemosdealcohol.com</span><span
        class="inline-block align-middle md:hidden visible">
        <img
          class="inline-block align-middle" src="https://market.tapit.com.co/arquivos/footer-icon-1.png"/>
        <img
          class="inline-block align-middle ml-1" src="https://market.tapit.com.co/arquivos/footer-icon-2.png"/>
        <img
          class="inline-block align-middle ml-1" src="https://market.tapit.com.co/arquivos/footer-icon-3.png"/></span>
      </div>
      <div class="w-full mt-4 sm:mt-1 order-6 md:w-1/3 md:pl-2 hidden md:block visible">
        <img
          class="inline-block align-middle" src="https://market.tapit.com.co/arquivos/footer-icon-1.png"/>
        <img
          class="inline-block align-middle ml-1" src="https://market.tapit.com.co/arquivos/footer-icon-2.png"/>
        <img
          class="inline-block align-middle ml-1" src="https://market.tapit.com.co/arquivos/footer-icon-3.png"/></div>
    </div>
  </div>
</footer>

// react-app/src/components/footer.component.js
import React from "react";
import DownloadFooter from './downloadFooter.component';

export default function FooterSection(props) {

  const social = i18next.t("Footer.Social", {returnObjects: true})
  const links = i18next.t("Footer.Links", {returnObjects: true})
  let firstMenu = [];
  let secondMenu = [];

  return (
    <footer
      className='bg-neutral-100 w-full mt-10 bg-right-bottom sm:bg-right bg-no-repeat bg-contain sm:bg-auto bg-footer border-t-2 border-primary-500'>
      <div className='container pt-8 px-4 md:px-0 mx-auto'>
        <div className='w-full sm:w-9/12 xl:w-9/12 px-4 inline-block'>
          <div className="inline-block align-top">
            <p
              className="text-primary-500 uppercase mb-6 font-bold text-xs tracking-widest">{i18next.t("Footer.TextTapit")}</p>
            {links.map((item, index) => {
              (index + 2) % 2 == 0 ?
                firstMenu.push(item)
                :
                secondMenu.push(item)
            })}
            <div className="w-1/2 inline-block align-top">
              <ul className='text-secondary-500'>
                {firstMenu.map((item, index) => {
                  return (
                    <li className="w-full inline-block align-top sm:pb-0 pb-3 mb-5" key={index}>
                      <a target="_blank" href={item.Url}>
                        {item.Name}
                      </a>
                    </li>
                  )
                })}
              </ul>
            </div>
            <div className="w-1/2 inline-block align-top">
              <ul className='text-secondary-500'>
                {secondMenu.map((item, index) => {
                  return (
                    <li className="w-full inline-block align-top sm:pb-0 pb-3 mb-5" key={index}>
                      <a target="_blank" href={item.Url}>
                        {item.Name}
                      </a>
                    </li>
                  )
                })}
              </ul>
            </div>
          </div>
        </div>
        <div className="w-full sm:w-3/12 xl:w-3/12 inline-block align-top px-4">
          <p
            className="text-primary-500 uppercase mb-6 font-bold text-xs tracking-widest">{i18next.t("Footer.TextFollow")}</p>
          <ul className='text-secondary-500'>
            {social.map((item, index) => {
              return (
                <li className="mb-5 w-1/2 sm:w-full inline-block" key={index}>
                  <a target="_blank" href={item.Url}>
                    <img src={item.Image} className="inline-block align-middle"/>
                    <span className="align-middle ml-3">{item.Name}</span>
                  </a>
                </li>
              )
            })}
          </ul>
        </div>
        <div className='w-full sm:w-9/12 xl:w-9/12 px-4 inline-block pt-4'>
          <div className="inline-block align-top w-full">
            <p
              className="text-primary-500 uppercase mb-6 font-bold text-xs tracking-widest">{i18next.t("Footer.Support.Title")}</p>
            <div className="w-1/2 inline-block align-top">
              <ul className='text-secondary-500'>
                <li className="w-full inline-block align-top sm:pb-0 pb-3 mb-5">
                  <a target="_blank" href={i18next.t("Footer.Support.Help.Url")}>
                    {i18next.t("Footer.Support.Help.Text")}
                  </a>
                </li>
                <li className="w-full inline-block align-top sm:pb-0 pb-3 mb-5">
                  <a target="_blank" href={i18next.t("Footer.Support.SIC.Url")}>
                    {i18next.t("Footer.Support.SIC.Text")}
                  </a>
                </li>
              </ul>
            </div>
            <div className="w-1/2 inline-block align-top">
              <ul className='text-secondary-500'>
                <li className="w-full inline-block align-top sm:pb-0 pb-3 mb-5 hidden">
                  <a target="_blank" href={i18next.t("Footer.Support.Contact.Url")}>
                    {i18next.t("Footer.Support.Contact.Text")}
                  </a>
                </li>
                <li className="w-full inline-block align-top sm:pb-0 pb-3 mb-5">
                  <a target="_blank" href={i18next.t("Footer.Support.Cancellation.Url")}>
                    {i18next.t("Footer.Support.Cancellation.Text")}
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <DownloadFooter isMobile={props.isMobile}/>

        <p className="px-2 py-6 text-xs">ZX VENTURES COLOMBIA S.A.S. NIT: 830.094.751-7 Dirección: Cra 53ª No. 127 – 35,
          Bogotá. Correo electrónico para notificaciones: impuestos@bogotabeercompany.com</p>

        <div className="border-t-2 border-neutral-500 py-5 px-5 md:px-0 flex flex-wrap">
          <div className="w-full mt-4 sm:mt-1 order-1 md:w-1/3 sm:w-3/5">
            <img className="inline-block align-middle"
                 src="https://market.tapit.com.co/arquivos/tap-it_black-orange.png"/>
            <p className="inline-block text-neutral-700 ml-1 pl-2 border-l border-neutral-600 align-middle text-xs">
              <span>Todos los derechos reservados © 2020</span>
            </p></div>
          <div className="w-full mt-4 sm:mt-1 order-2 sm:order-3 sm:w-3/5 md:order-4 md:w-1/3 text-xs text-neutral-700">
            Prohíbase el expendio de bebidas embriagantes a menores de edad.
          </div>
          <div
            className="w-full mt-4 sm:mt-1 order-3 sm:order-5 sm:w-3/5 md:order-2 md:w-1/3 md:pl-12 text-xs text-neutral-700">
            El exceso de alcohol es perjudicial para la salud.
          </div>
          <div
            className="w-full mt-4 sm:mt-1 order-4 sm:order-2 sm:w-2/5 sm:pl-4 md:order-5 md:w-1/3 md:pl-12 text-xs text-neutral-700">
            No comparta este contenido con menores de edad.
          </div>
          <div
            className="w-full mt-4 sm:mt-1 order-5 sm:order-4 sm:w-2/5 sm:pl-4 md:order-3 md:w-1/3 md:pl-2 text-xs text-black font-bold">
            <span className="inline-block align-middle">www.hablemosdealcohol.com</span><span
            className="inline-block align-middle md:hidden visible">
        <img
          className="inline-block align-middle" src="https://market.tapit.com.co/arquivos/footer-icon-1.png"/>
        <img
          className="inline-block align-middle ml-1" src="https://market.tapit.com.co/arquivos/footer-icon-2.png"/>
        <img
          className="inline-block align-middle ml-1"
          src="https://market.tapit.com.co/arquivos/footer-icon-3.png"/></span>
          </div>
          <div className="w-full mt-4 sm:mt-1 order-6 md:w-1/3 md:pl-2 hidden md:block visible">
            <img
              className="inline-block align-middle" src="https://market.tapit.com.co/arquivos/footer-icon-1.png"/>
            <img
              className="inline-block align-middle ml-1" src="https://market.tapit.com.co/arquivos/footer-icon-2.png"/>
            <img
              className="inline-block align-middle ml-1" src="https://market.tapit.com.co/arquivos/footer-icon-3.png"/>
          </div>
        </div>
      </div>
    </footer>
  )
}
