// home/src/app/header/header.component.ts
import {Component, OnDestroy} from '@angular/core';
import {of} from 'rxjs';
import {environment} from '../../environments/environment';
import {UserAccount} from '../user/user-account';
import { AngularFireAuth } from '@angular/fire/auth';
import { AngularFirestore } from '@angular/fire/firestore';
import { switchMap } from 'rxjs/operators';
import { DataRepoService } from '../services/data-repo.service';


@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnDestroy {
  user: UserAccount;
  marketUrl = environment.marketUrl;
  showLoginButton = false;
  showMicrogifting = false;
  total: any;
  showCuponeraButton$: false;

  constructor(
    private angularFireAuth: AngularFireAuth,
    private angularFirestore: AngularFirestore,
    private dataRepoService: DataRepoService
  ) {
    this.angularFireAuth.user
    .pipe(switchMap(user => {
      return user ? this.angularFirestore.collection('user_account_tap').doc(user.uid).valueChanges() : of(null);
    }))
    .subscribe(user => {
      this.user = user;
      this.showLoginButton = !this.user;
    })
    this.dataRepoService.getShowWallet()
    .subscribe((data:  any) => {
      this.showCuponeraButton$ = data.data;
    })
  }

  setMenu(event: any) {
    if (event.target.checked) {
      document.body.classList.add('overflow-hidden');
    } else {
      document.body.classList.remove('overflow-hidden');
    }
  }

  loginCloseMenu() {
    document.getElementById('toggleMenu').click()
  }

  ngOnDestroy(): void {
    //this.userSubscription.unsubscribe();
  }

  ssoOpen():void {
    ssoApp.showApp();
  }
}

<header class='border-b border-neutral-500 bg-white z-10 relative'>
  <nav class="block sm:hidden" role="navigation">
    <div class="absolute block w-full" id="menuToggle">
      <input (click)="setMenu($event)" class="block absolute" id="toggleMenu" type="checkbox" aria-label="toggle menu">
      <div (click)="loginCloseMenu()" class="background"></div>
      <img class="img-menu block" src="../assets/images/hMenu.svg" width="26" alt="Abrir menú">

      <ul *ngIf="!user" class="fixed w-10/12 p-5 bg-neutral-100 h-full top-0 border-4 border-white text-sm sm:text-base"
        id="menu">
        <li class="py-2">
          <img class="w-2/3" src="../assets/images/tap-it_black-orange.svg" alt="Tapit logo">
        </li>
        <li class="py-2">
          <button
            class="app-button border-2 border-primary-500 bg-primary-500 text-white text-center p-3 py-2 text-sm cursor-pointer uppercase hover:bg-primary-300 hover:border-primary-300 w-full"
            (click)="loginCloseMenu();ssoOpen();">
            REGÍSTRATE
          </button>
        <li class="py-2">
          <button (click)="loginCloseMenu();ssoOpen();"
            class="app-button border-2 border-black bg-white text-black text-center p-3 py-2 text-sm cursor-pointer uppercase hover:bg-black hover:text-white w-full">
            INICIA SESIÓN
          </button>
        </li>
        <li>
          <img class="absolute icon-close" src="../assets/images/ic_close.svg" alt="Cerrar menú" width="30">
        </li>
      </ul>

      <ul *ngIf="user"
        class="fixed w-10/12 p-6 bg-neutral-100 pt-2 h-full top-0 border-4 border-white text-sm sm:text-base" id="menu">
        <li class="cursor-pointer inline-block align-middle focus:outline-none p-0">
          <a href="/app/user/profile"><img src="../assets/images/profile-placeholder.png" width="100"
              alt="Icono Perfil"></a>
        </li>
        <li (click)="loginCloseMenu()"
          class="font-bold text-md uppercase text-primary-500 cursor-pointer block mr-4 align-middle focus:outline-none py-4">
          <a href="/app/user/profile">
            <span class="block">{{ user.firstName }} {{ user.lastName }}</span>
            <span class="text-neutral-700 normal-case text-xs font-normal block mt-2">{{user.email}}</span>
          </a>
        </li>
        <li *ngIf="user" class="inline-block  align-middle border-b border-neutral-500 w-full py-4"
          (click)="loginCloseMenu()">
          <a href="/app/gana-puntos"
            class="font-bold text-md uppercase text-neutral-700 inline-block align-middle focus:outline-none">
            <img class="inline-block align-middle cuppon-icon" src="assets/images/union-gray.png" alt="">
            <span class="inline-block align-middle ml-2">Gana Puntos</span>
          </a>
        </li>
        <li *ngIf="user" class="inline-block  align-middle border-b border-neutral-500 w-full py-4"
          (click)="loginCloseMenu()">
          <a href="/app/como-redimir"
            class="font-bold text-md uppercase text-neutral-700 inline-block align-middle focus:outline-none">
            <img class="inline-block align-middle cuppon-icon" src="assets/images/como-redimir-icon-gray.png" alt="">
            <span class="inline-block align-middle ml-2">¿Cómo Redimir?</span>
          </a>
        </li>
        <li class="inline-block align-middle border-b border-neutral-500 w-full py-4">
          <a [href]="marketUrl"
            class="font-bold text-md uppercase text-neutral-700 inline-block align-middle focus:outline-none"><i
              class="uil uil-store text-lg"></i> Redimir Puntos</a>
        </li>
        <li *ngIf="user && showCuponeraButton$" class="inline-block  align-middle border-b border-neutral-500 w-full py-4"
          (click)="loginCloseMenu()">
          <a href="/app/wallet"
            class="font-bold text-md uppercase text-neutral-700 inline-block align-middle focus:outline-none">
            <img class="inline-block align-middle cuppon-icon" src="assets/images/ticket.png" alt="">
            <span class="inline-block align-middle ml-2">Cuponera</span>
          </a>
        </li>
        <li *ngIf="user" class="inline-block  align-middle border-b border-neutral-500 w-full py-4"
          (click)="loginCloseMenu()">
          <a href="https://hayplan.tapit.com.co"
            class="font-bold text-md uppercase text-neutral-700 inline-block align-middle focus:outline-none">
            <img class="inline-block align-middle cuppon-icon" src="https://bavariaco.vteximg.com.br/arquivos/Vectorplan-icon.svg" alt="">
            <span class="inline-block align-middle ml-2">Hay Plan</span>
          </a>
        </li>
        <li *ngIf="user" class="inline-block  align-middle border-b border-neutral-500 w-full py-4"
          (click)="loginCloseMenu()">
          <a href="/" class="font-bold text-md uppercase text-neutral-700 inline-block align-middle focus:outline-none">
            <img class="inline-block align-middle cuppon-icon" src="https://bavariaco.vteximg.com.br/arquivos/Vectorhome-icon.svg" alt="">
            <span class="inline-block align-middle ml-2"> Home</span>
          </a>
        </li>


        <li *ngIf="showMicrogifting" class="inline-block align-middle border-b border-neutral-500 w-full py-4">
          <a class="font-bold text-md uppercase text-neutral-700 inline-block align-middle focus:outline-none"
            href="{{marketUrl}}/comprar-regalo">
            <img class="text-base inline-block align-middle leading-none mx-1" src="assets/images/red-heart.png"
              style="max-width: 20px;">
            RESCATE POKER ROJA
          </a>
        </li>
        <li class="inline-block align-middle border-b border-neutral-500 w-full py-4 hidden">
          <a (click)="loginCloseMenu()"
            class="font-bold text-md uppercase text-neutral-700 inline-block align-middle focus:outline-none app-link"
            routerLink="/user/codes" routerLinkActive="active"><i class="uil uil-ticket text-lg"
              queryParamsHandling="merge"></i> Mis Códigos</a>
        </li>
        <li class="inline-block align-middle w-full py-4">
          <a (click)="loginCloseMenu()"
            class="font-bold text-md uppercase text-neutral-700 inline-block align-middle focus:outline-none app-link"
            href="/app/user/profile" routerLinkActive="active"><i class="uil uil-user-circle text-lg"
              queryParamsHandling="merge"></i> Perfil</a>
        </li>
        <li><img class="absolute icon-close" src="../assets/images/ic_close.svg" width="30" alt="cerrar"></li>
      </ul>
    </div>
  </nav>
  <!-- Desktop Navigation -->
  <div class="container mx-auto md:px-4">
    <div class="w-full py-2 px-5 sm:px-0 flex items-center">
      <div class="flex-1 text-left">
        <ul>
          <li class="inline-block align-middle">
            <img class="main-logo ml-12 sm:ml-0" src="assets/images/tapit-logo.png" style="width: 70px;"
              alt="tapit logo" />
          </li>

          <li *ngIf="user" class="hidden md:inline-block align-middle ml-8">
            <a href="/app/gana-puntos"
              class="font-bold text-sm uppercase text-neutral-700 inline-block mr-6 align-middle focus:outline-none">
              <img class="inline-block align-middle cuppon-icon" src="assets/images/Union.png" alt="">
              <span class="inline-block align-middle ml-1"> Gana Puntos</span></a>
          </li>
          <li *ngIf="user" class="hidden md:inline-block align-middle ml-8">
            <a href="/app/como-redimir"
              class="font-bold text-sm uppercase text-neutral-700 inline-block mr-6 align-middle focus:outline-none">
              <img class="inline-block align-middle cuppon-icon" src="assets/images/beer-icon-orange.png" alt="">
              <span class="inline-block align-middle ml-1">¿Cómo Redimir?</span></a>
          </li>
          <li *ngIf="user" class="hidden md:inline-block align-middle ml-8">
            <a [href]="marketUrl"
              class="font-bold text-sm uppercase text-neutral-700 inline-block mr-6 align-middle focus:outline-none"><i
                class="uil uil-store text-base inline-block align-middle leading-none"></i> <span
                class="inline-block align-middle ml-1">Redimir Puntos</span></a>
          </li>
          <li *ngIf="user && showCuponeraButton$" class="hidden md:inline-block align-middle">
            <a href="/app/wallet"
              class="font-bold text-sm uppercase text-neutral-700 inline-block mr-6 align-middle focus:outline-none">
              <img class="inline-block align-middle cuppon-icon" src="assets/images/ticket.png" alt="">
              <span class="inline-block align-middle ml-1">Cuponera</span>
            </a>
          </li>
          <li *ngIf="user && showMicrogifting" class="hidden sm:inline-block align-middle">
            <a class="font-bold text-sm uppercase text-neutral-700 inline-block mr-10 align-middle focus:outline-none"
              href="{{marketUrl}}/comprar-regalo">
              <img class="text-base inline-block align-middle leading-none mr-1" src="assets/images/red-heart.png"
                style="max-width: 15px;" alt="red heart">
              <span class="inline-block align-middle">RESCATE POKER ROJA</span>
            </a>
          </li>
          <li *ngIf="user" class="hidden align-middle">
            <a class="font-bold text-sm uppercase text-neutral-700 inline-block mr-10 align-middle focus:outline-none app-link"
              routerLink="/user/codes" routerLinkActive="active"><i
                class="uil uil-ticket text-base inline-block align-middle leading-none" queryParamsHandling="merge"></i>
              <span class="inline-block align-middle">Mis Códigos</span></a>
          </li>
        </ul>
      </div>
      <div class="text-right" style="min-height: 38px;">
        <ul *ngIf="user" class="relative">
          <ul class="relative inline-block sm:hidden">
            <li class="inline-block ml-4 align-middle">
              <span class="text-sm font-bold block text-neutral-700">Tus puntos</span>
              <span class="text-sm font-bold block text-primary-500">{{
                user.points | number: "1.0"
                }}</span>
            </li>
          </ul>
          <ul class="relative hidden sm:inline-block py-2 profile-header" routerLinkActive="active">
            <li
              class="font-bold text-sm uppercase text-neutral-700 cursor-pointer inline-block mr-4 align-middle focus:outline-none app-link">
              <i class="uil uil-user-circle text-base inline-block align-middle inline-block align-middle"
                queryParamsHandling="merge"></i>
              <a href="/app/user/profile"><span class="inline-block align-middle">{{ user.firstName }}</span></a>
            </li>
            <li class="relative h-6 top-0 bottom-0 border-l border-neutral-500 inline-block align-middle"></li>
            <li class="inline-block ml-4 align-middle">
              <small class="text-xs font-bold inline-block text-neutral-700 relative points-text">Pts. </small>
              <span class="text-sm font-bold inline-block text-primary-500"> {{
                user.points | number: "1.0"
                }}</span>
            </li>
          </ul>
        </ul>
        <ul *ngIf="showLoginButton" class="flex-grow relative hidden sm:block">
          <li class="float-right">
            <button
              class="app-button md:inline-block hidden border-2 border-black bg-white text-black text-center p-3 py-2 text-sm cursor-pointer uppercase hover:bg-black hover:text-white"
              (click)="ssoOpen()">INICIA SESIÓN</button>
          </li>
          <li class="float-right">
            <button
              class="app-button md:inline-block hidden border-2 border-primary-500 bg-primary-500 text-white text-center p-3 py-2 text-sm cursor-pointer mx-2 uppercase hover:bg-primary-300 hover:border-primary-300"
              (click)="ssoOpen()">REGÍSTRATE</button>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

// react-app/src/components/header.component.js
import React from "react";
import UrlBuilderService from "../services/url-builder.service";

export default function Header(props) {
  console.log(props)
  function setMenu(e) {
    if (e.target.checked) {
      document.body.classList.add('overflow-hidden');
    } else {
      document.body.classList.remove('overflow-hidden');
    }
  }

  function loginCloseMenu() {
    document.getElementById('toggleMenu').click()
  }

  return (

    <header className='border-b border-neutral-500 bg-white mb-6'>
      <div className='container md:px-4'>
        <nav role="navigation" className="block sm:hidden">
          <div id="menuToggle" className="absolute block w-full">
            <input type="checkbox" onClick={setMenu} id='toggleMenu' className="block absolute"/>
            <div onClick={loginCloseMenu} className="background"></div>
            <img className='img-menu block' width="26" src='../assets/images/hMenu.svg'/>
            <ul className="fixed w-10/12 p-6 bg-neutral-100 pt-2 h-full top-0 border-4 border-white" id="menu">
              <li className="py-2">
                <img className="w-2/3" src={i18next.t("BillLayout.Header.Logo")}/>
              </li>
              <li className="py-2">
                <a
                  className="app-button border-2 border-primary-500 bg-primary-500 text-white w-full text-center p-3 text-sm"
                  href={UrlBuilderService.buildUrl('angular', 'auth/login')}>
                  {i18next.t("BillLayout.Header.LoginText")}
                </a>
              </li>
              <img width="30" className="absolute icon-close" src={i18next.t("BillLayout.Header.IconClose")}/>
            </ul>
          </div>
        </nav>
        <div className="w-full py-2">
          <div className="inline-block text-left w-1/2 mb-0 align-middle">
            <ul>
              <li>
                <img className="main-logo ml-12 sm:ml-0 inline-block align-middle" src={i18next.t("Header.Logo")}
                     style={{width: '70px'}}/>
              </li>
            </ul>
          </div>
          <div className="inline-block text-center md:text-right w-1/2 align-middle text-right pr-2">
            
            <ul>
              <li className="inline-block">
                <a
                  className="app-button border-2 border-primary-500 bg-primary-500 text-white text-center p-3 py-2 text-sm cursor-pointer mx-2 uppercase hover:bg-primary-300 hover:border-primary-300"
                  onClick={()=>props.showSSOPopup('/sign-up')}>
                  {i18next.t("BillLayout.Header.SignupText")}
                </a>
              </li>
              <li className="inline-block">
                <a
                  className="app-button border-2 border-black bg-white text-black text-center p-3 py-2 text-sm cursor-pointer uppercase hover:bg-black hover:text-white"
                  onClick={()=>props.showSSOPopup('/login')}>
                  {i18next.t("BillLayout.Header.LoginText")}
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>

    </header>
  )


}
